### PR TITLE
Migrate from express v3 to v4

### PR DESCRIPTION
**Pull request by shinnn**
* Updated [minimatch](https://github.com/isaacs/minimatch) to v2.0.0.
* [Migrated from express v3 to v4](https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x)
* update package.json and .travis.yml

### CODE REVIEW

**Comment by shakyShane** [comment]
Thanks dude! :)

**Comment by shinnn** [comment]
Could you release a patch-updated version?

**Comment by shakyShane** [comment]
done :)

**Comment by shinnn** [comment]
:+1:

**Pull request merged**
